### ISSUE TITLE
Set `bottle :unneeded` is deprecated

### ISSUE THREAD

**Issue by zainafifaldi** [go-rel/homebrew-tap#1]
I tried to tap and install using homebrew (following [this doc](https://go-rel.github.io/migration/#running-migration)), but I got this error:
```bash
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/go-rel/homebrew-tap/Formula/rel.rb
rel: wrong number of arguments (given 1, expected 0)
Error: Cannot tap go-rel/tap: invalid syntax in tap!
```

Tried to pull this repo manually, it was successful. But, I got the same error when do `brew install rel`.

I found that the error comes from [this code](https://github.com/go-rel/homebrew-tap/blob/main/Formula/rel.rb#L10). After did some googling, I think `bottle :unneeded` syntax has already been deprecated, and there's no replacement for that.

How about removing this line of code?
Cc: @Fs02

**Comment by Fs02** [comment]
Thanks for the report

This codes is generated by goreleaser, I guess we only need to upgrade the goreleaser version
https://github.com/goreleaser/goreleaser/pull/2591

**Comment by Fs02** [comment]
oh, looks like it was added from 0.38.0 🤔 
https://github.com/go-rel/homebrew-tap/commit/01c6e062be79155249567582a94c2538406532bf

**Comment by Fs02** [comment]
oh, I was releasing from local at the time because of problem with CI
let's remove it manually

**Comment by Fs02** [comment]
seems fixed now, thank you

**Comment by zainafifaldi** [comment]
Great! Thank you for your support and fast response @Fs02. I really appreciate that 🙌
